server:
  port: 8081

spring:
  application:
    name: finance-service
  mvc:
    problem-details:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Sentinel

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Sentinel
          jwk-set-uri: http://keycloak:8080/realms/Sentinel/protocol/openid-connect/certs
